#!/bin/bash

# Script to help set up the GitHub repository
# Run this after creating the repository on GitHub

echo "Setting up Euler Cluster Guide repository for GitHub"
echo "===================================================="
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Create a new repository on GitHub:"
echo "   - Go to: https://github.com/organizations/leggedrobotics/repositories/new"
echo "   - Repository name: euler-cluster-guide"
echo "   - Description: Comprehensive guide for using Docker containers on Euler cluster at ETH Zurich"
echo "   - Public repository"
echo "   - Do NOT initialize with README, .gitignore, or license"
echo ""
echo "2. After creating the repository, run these commands:"
echo ""
echo "   git remote add origin https://github.com/leggedrobotics/euler-cluster-guide.git"
echo "   git push -u origin main"
echo ""
echo "3. Enable GitHub Pages:"
echo "   - Go to Settings > Pages"
echo "   - Source: Deploy from a branch"
echo "   - Branch: main"
echo "   - Folder: /docs"
echo "   - Save"
echo ""
echo "4. The site will be available at:"
echo "   https://leggedrobotics.github.io/euler-cluster-guide/"
echo ""
echo "5. (Optional) Update README badges and links after repository is live"