title: RSL Euler Cluster Guide
description: A comprehensive guide for using Docker containers on the Euler cluster at ETH Zurich - Robotics Systems Lab
baseurl: "/euler-cluster-guide"
url: "https://leggedrobotics.github.io"

# Theme
remote_theme: just-the-docs/just-the-docs@v0.7.0
color_scheme: light

# Enhanced theme settings for better width and layout
callouts_level: quiet
callouts:
  highlight:
    color: blue
  important:
    title: Important
    color: red
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: yellow

# Site settings
logo: "/assets/images/logo.png"
search_enabled: true
search.button: true
heading_anchors: true
permalink: pretty

# Aux links for top navigation
aux_links:
  "GitHub":
    - "https://github.com/leggedrobotics/euler-cluster-guide"
  "RSL Lab":
    - "https://rsl.ethz.ch"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Footer
footer_content: "Copyright &copy; 2025 Legged Robotics Lab, ETH Zurich. Distributed under the <a href=\"https://github.com/leggedrobotics/euler-cluster-guide/blob/main/LICENSE\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Back to top
back_to_top: true
back_to_top_text: "Back to top"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections for just-the-docs
collections:
  # Define collections for your content if needed
  
# Navigation Structure
nav_enabled: true
nav_sort: case_sensitive

# External links
nav_external_links:
  - title: ETH Euler Docs
    url: https://scicomp.ethz.ch/wiki/Euler
    hide_icon: false